### ISSUE TITLE
kube-bench for CIS 1.7 has a check for PodSecurityPolicy, which is removed in Kubernetes v.1.25

### ISSUE THREAD

**Issue by Skybladev2** [aquasecurity/kube-bench#1451]
**Overview**

kube-bench for CIS 1.7 (which correlates with Kubernetes v.1.25) has a [check for PodSecurityPolicy](https://github.com/aquasecurity/kube-bench/blob/main/cfg/cis-1.7/master.yaml#L488-L507), which is [removed in Kubernetes v.1.25](https://kubernetes.io/docs/concepts/security/pod-security-policy/). Thus, this test can never succeed and distracts users.

**How did you run kube-bench?**

```
 kubectl apply -f job-master.yaml
```

**What happened?**

```
[WARN] 1.2.12 Ensure that the admission control plugin SecurityContextDeny is set if PodSecurityPolicy is not used (Manual)
```

**What did you expect to happen:**

I expect the absense of said item.

**Comment by mozillazg** [comment]
@Skybladev2 Thanks for reporting. Because we follow the CIS Kubernetes Benchmark v1.7.0 we need this check to be removed from the benchmark before we remove them from kube-bench (though you can of course modify the test yaml that you run with in your own environment in the mean time).

<img width="944" alt="image" src="https://github.com/aquasecurity/kube-bench/assets/485054/726cc9dc-6f36-4da0-8d5b-e0fcb58e4ba6">


https://workbench.cisecurity.org/benchmarks/11107/sections/1519432

**Comment by Jeansen** [comment]
I already contacted the CIS. There are more, obsolete entries and references. I think the whole Benchmark needs some review.
