### ISSUE TITLE
kube-bench does not support snap based kubernetes installations

### ISSUE THREAD

**Issue by CalvinHartwell** [aquasecurity/kube-bench#158]
Hi all,

The kube-bench scans do not currently detect snap based installations, the paths for the systemd units and the args are in different locations. This messes up the kubelet and master scans for Canonical/Ubuntu based installations of Kubernetes. 

I will put together a proper list of bugs and raise a PR. 

Cheers,

- Calvin

**Comment by ttousai** [comment]
Hello @CalvinHartwell ! Looking forward to the PR.

**Comment by CalvinHartwell** [comment]
More information on snap based package structure: [https://docs.snapcraft.io/snaps/structure](https://docs.snapcraft.io/snaps/structure), I'm hoping to get this done this week or next week to fix Aqua support for CDK.

**Comment by nicorikken** [comment]
@sabbour Indeed, this is a broader issue. We run kube-proxy, kubelet and kubeapiserver in containers (Docker/Rocket) on the nodes, which also messes up running kube-bench, because the binaries are not available. Despite the containerized processes being available through `ps`. We ended up adding the binaries as dummies to trick kube-bench into executing 😆

**Comment by lizrice** [comment]
Ah, thanks @nicorikken, that's an interesting clue! Could you expand on what you mean by "adding the binaries as dummies"? 

Adding the file locations and binary names into the config files *should* just work if the processes are available through ps (modulo whether ps itself is available). Also, the dependency on finding either kubectl or kubelet executable can be removed by specifying a particular version config with --version.
