### ISSUE TITLE
Master 1.1.30 and 1.1.39 are the same

### ISSUE THREAD

**Issue by BarryWilliams** [aquasecurity/kube-bench#244]
Benchmarks Master [1.1.30 ](https://github.com/aquasecurity/kube-bench/blob/2eef3e8ad2e94d8ecbf1daeb13e04acda7196fd7/cfg/1.11/master.yaml#L489-L503)and [1.1.39](https://github.com/aquasecurity/kube-bench/blob/2eef3e8ad2e94d8ecbf1daeb13e04acda7196fd7/cfg/1.11/master.yaml#L645-L659) are the same. The only difference is the remediation text, but that appears to be logically the same.

1.1.39 is not the same in CIS benchmark. This is from CIS:
`Ensure that the --authorization-mode argument includes RBAC` - Turn on Role Based Access Control.

From the 01-31-2019 CIS Kubernetes Benchmark PDF

**Comment by lizrice** [comment]
@yoavrotems please could you take a look at this in the 1.13
config?

**Comment by yoavrotems** [comment]
Those tests are the same, we just look for different things in the output.
From Benchmark v1.4 for kubernetes 1.13
here is the 1.30 audit and what we are looking for at the output:
----------------1.30---------------
"Audit:
Run the following command on the master node:
ps -ef | grep kube-apiserver
Verify that the --tls-cipher-suites argument is set as outlined in the remediation
procedure below"
-----------------------------------
And here is the 1.39 audit and what we are looking for in the output:
----------------1.39---------------
"Audit:
Run the following command on the master node:
ps -ef | grep kube-apiserver
Verify that the --authorization-modeargument exists and is set to a value to include RBAC"
-----------------------------------

As you can see it's the same logic and test but with different values to check and different remediation

**Comment by lizrice** [comment]
Oh, sorry, I have led you astray @yoavrotems by asking you to check the 1.13 files. The numbering has changed between 1.11 and 1.13. Please can you check against the 1.3 Benchmark? It does look like we have duplicate tests in the 1.11 config files (see the links that @BarryWilliams posted above)

**Comment by yoavrotems** [comment]
Ok checked the 1.3 Benchmark for kubernetes 1.11, and in cis and the problem is the cis logic,
basically the test could be the same or different.

Benchmark v1.3 for kubernetes 1.11:
1.30
> Audit:
Run the following command on the master node: ps -ef | grep kube-apiserver
Verify that the --tls-cipher-suites argument is set as outlined in the remediation procedure below.

1.39
> Audit:
Run the following command on the master node: ps -ef | grep kube-apiserver
Verify that the --tls-cipher-suites argument is set as appropriate.

I believe 1.39 should be changed to manual because it supposed to be set by user preference

**Comment by lizrice** [comment]
Looks to me that in benchmark 1.3, test 1.1.39 is a duplicate of 1.1.30. But since we follow the benchmark, we should keep that duplicate test, so let's leave the files in 1.11 as they are.
