### ISSUE TITLE
1.4.21 test title does not line up with CIS

### ISSUE THREAD

**Issue by BarryWilliams** [aquasecurity/kube-bench#245]
[This test title is wrong](https://github.com/aquasecurity/kube-bench/blob/master/cfg/1.13/master.yaml#L1216)

It should be `1.4.21 Ensure that the Kubernetes PKI key file permissions are set to 600 (Scored)` According to the 1.13 CIS Benchmark

**Comment by yoavrotems** [comment]
Thanks for bringing it to our attention, the title is wrong but the test is fine, we fixed it :) https://github.com/aquasecurity/kube-bench/pull/246.

**Comment by src7** [comment]
Hello, better late than never : `certificate` should be replaced by `key`, this is really confusing otherwise...

**1.4.20** Ensure that the Kubernetes PKI **certificate** file permissions are set to **644** or more restrictive (Scored)
**1.4.21** Ensure that the Kubernetes PKI **certificate** file permissions are set to **600** or more restrictive (Scored)
