### ISSUE TITLE
Need better docs for configuring kubeconfig file locations for 2.2.1, 2.2.2, 2.2.5, 2.2.6

### ISSUE THREAD

**Issue by cjschaef** [aquasecurity/kube-bench#255]
When the configuration files for the `2.2.1`, `2.2.2`, `2.2.5`, and `2.2.6` checks do not exist, the checks will fail since they do not meet one of the expected outputs, since the result is an empty string, which doesn't match the provided values.

The alternative at the moment is to skip the checks completely. But support to handle when the files don't exist, given the check does the same, should be available.

**Comment by cjschaef** [comment]
There may be similar checks that check if a file exists, prior to checking permissions or owner/group, and an empty string comparison would fail. Again, if the check is verifying if the file exists prior to checking the permissions, it should fail when the fail doesn't exist.
`"/bin/sh -c 'if test -e $kubeletkubeconfig; then stat -c %a $kubeletkubeconfig; fi'"`

**Comment by lizrice** [comment]
In general it would **not** be correct to pass tests if the file doesn't exist in the expected location. If there's a kubeconfig file with loose permissions, but we are not even checking permissions on that file, this should definitely fail the CIS check. 

The right thing to do is to update the config file to specify the location(s) of the file(s) on this particular system. This is why the file locations are specified in YAML (`defaultkubeconfig` in `config.yaml`), so that they can be modified as needed to reflect different environments. We could do a better job of [documenting](https://github.com/aquasecurity/kube-bench/issues/235) this. 

The spec for 2.2.5-2.2.6 does say "if `kube-proxy` is running" so arguably we could be adding to the audit command to only fail this if there is a kube-proxy binary running also. Since this is a rare occurence (afaik) this can also be handled by users who aren't using `kube-proxy` marking these tests as `type: skip`. 

If it's possible to auto-detect the locations of some or all of these files, that's something we can consider as an enhancement

**Comment by cjschaef** [comment]
Okay, better auto-detection would be good. If there are components that don't utilize configuration files it would be better to pass a check than skip it in my opinion, but if that is the design decision that is being followed, skipping the security check will have to be the result.

**Comment by ttousai** [comment]
@lizrice specifying a list of standard possible locations in config.yaml for kube-bench to check covers the auto-detection of files IMO.

We have improved our documentation on configuration #235 since this issue was created so I think we can close this. The new and improved documentation is under `docs/README.md`.

I think we can close this issue on that note.

**Comment by lizrice** [comment]
@ttousai we still have some info in the main README that is better documented in docs/README.md. Please can you update the main README to remove the duplicate info and refer to the docs/README.md instead?

**Comment by ttousai** [comment]
@lizrice I have created a separate issue #372 to track removing the duplicate info in README.md.
