### ISSUE TITLE
Remove cipher suites TLS_RSA_WITH_AES_256_GCM_SHA384 and TLS_RSA_WITH_AES_128_GCM_SHA256

### ISSUE THREAD

**Issue by zhedahht** [aquasecurity/kube-bench#303]
TLS_RSA_WITH_AES_256_GCM_SHA384 and TLS_RSA_WITH_AES_128_GCM_SHA256 have been marked as weak cipher suites by SSL Labs, and we should not include them in tls-cipher-suites.

**Comment by simar7** [comment]
Thanks @zhedahht I've added a PR to tackle this https://github.com/aquasecurity/kube-bench/pull/308

**Comment by lizrice** [comment]
Sorry to be slow to respond on this. Because we follow the CIS Kubernetes Benchmark we need these cipher suites to be removed from the benchmark before we remove them from kube-bench (though you can of course modify the test yaml that you run with in your own environment in the mean time). I am raising a ticket on the CIS workbench about it.

**Comment by lizrice** [comment]
Ticket raise here: https://workbench.cisecurity.org/benchmarks/1370/tickets/8550
