### ISSUE TITLE
Info: Kube bench master node results for ETCD

### ISSUE THREAD

**Issue by jvaibhav123** [aquasecurity/kube-bench#306]
Dear Team,

We were running kube bench in production and we came across failures in etcd test cases.
[FAIL] 1.4.7 Ensure that the etcd pod specification file permissions are set to 644 or more restrictive (Scored)
[FAIL] 1.4.8 Ensure that the etcd pod specification file ownership is set to root:root (Scored)
[FAIL] 1.4.11 Ensure that the etcd data directory permissions are set to 700 or more restrictive (Scored)
[FAIL] 1.4.12 Ensure that the etcd data directory ownership is set to etcd:etcd (Scored)

We have deployed etcd on separate physical nodes.  so will above use cases valid for our use case as test case specifies pod specification?

++++++

[FAIL] 1.2.2 Ensure that the --address argument is set to 127.0.0.1 (Scored).
[FAIL] 1.3.7 Ensure that the --address argument is set to 127.0.0.1 (Scored)

Our cluster is build using kubeadm and by default address is populated as 0.0.0.0 so not sure if this should considered as failed in our case. Could you please suggest?

+++++++

[FAIL] 1.1.21 Ensure that the --kubelet-certificate-authority argument is set as appropriate (Scored).

In case of cluster installation using kubeadm where kubeadm takes care of certificate stuff so will it required to set this parameter?

I am not sure if there is any forum where i can ask these questions hence raised ticket for the same.

Thanks in advance.

Regards,
Vaibhav Joshi

**Comment by lizrice** [comment]
Hi @jvaibhav123, as you probably know, the kube-bench tests follow the [CIS Kubernetes Benchmark](cisecurity.org)

I recently raised a ticket about moving the etcd tests into a separate section to allow for the situation where etcd isn’t installed onto the same machine as the kubernetes master. 

Some folks from SIG Cluster Lifecycle are working with us and the CIS community on getting it so that the kubeadm installing and the CIS benchmark are aligned. If you’d like to join the discussion on this the CIS community is at [workbench.cisecurity.org](workbench.cisecurity.org)

We’ll keep the kube-bench tests in line with the benchmark, but if you want to modify the test files for your own environment you can simply edit the test YAML. One option is to mark them as `type: skip` - this will give you an INFO line (to remind you that the test exists) but won’t actually run the test.
