### ISSUE TITLE
suspicious looking flags in some ocp-3.11 tests

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-bench#408]
Should the `flag` field really be `authorization-mode: Webhook` in test 7.3 in ocp-3.11/node.yaml, or just `authorization-mode`? 

Similar question for 7.5, 7.9, 7.10, 7.13 (maybe others)

**Comment by yoavrotems** [comment]
I think it should because in the explanation we have the following  

> Unauthenticated/Unauthorized users have no access to OpenShift nodes. The kubelet flag
authorization-mode is explicitly set to WebHook

But in the remediation we do have that:

> Since Webhook is the default value, the authorization-mode configuration is not needed in
node-config. If it is configured, ensure the value is only set to ‘Webhook’. The node systemd
service (atomic-openshift-node) will not start if the configuration value is set to anything other
than Webhook.
So you could say we don't need to test because if present and not set webhook it won't work.
But I think its more informative the way it is. 
WDYT?

**Comment by lizrice** [comment]
I meant literally the `flag` field in the YAML file is `authorization-mode: Webhook`. Shouldn't the `flag` just be `authorization-mode` and the value we test it against be `Webhook`?

**Comment by yoavrotems** [comment]
OHHH yes I get what you mean.
Yes I think you are correct and it's kind of useless repetition.
I will fix it
