### ISSUE TITLE
getting 'Version check failed' running 'kubectl apply -f job.yaml' on AKS

### ISSUE THREAD

**Issue by hectoralicea** [aquasecurity/kube-bench#425]
Trying to run this on an AKS cluster (version 1.13.10) in Azure.  I got a similar error to below so I changed the command to specify the server version in job-node.yaml as was mentioned in [issue 312](https://github.com/aquasecurity/kube-bench/issues/312) as such:
```
command: ["kube-bench", "node", "--version", "1.13"]
```

Following is how I ran the job and how I retrieved the error.
```
MacBook-Air:kube-bench hector$ kubectl apply -f job.yaml 
job.batch/kube-bench created
MacBook-Air:kube-bench hector$ kc get pods
NAME               READY   STATUS   RESTARTS   AGE
kube-bench-q6q9w   0/1     Error    0          10s
kube-bench-qxqts   0/1     Error    0          14s
MacBook-Air:kube-bench hector$ kc logs kube-bench-q6q9w

Version check failed: need kubectl or kubelet binaries to get kubernetes version
Alternatively, you can specify the version with --version
```
I saw some issues that make me doubt this will work on an AKS cluster.  Please advise if AKS is supported.

**Comment by hectoralicea** [comment]
Ok, I was able to get this to run by adding the --version option to the job.yaml.  Following is the changes I made.

```
#       command: ["kube-bench"]
        command: ["kube-bench", "--version", "1.13"]
```

**Comment by lizrice** [comment]
Maybe we should add the version in to the job yaml files explicitly, and/or have a job-aks.yaml file. Wdyt @robertojrojas?

**Comment by robertojrojas** [comment]
It should be fixed with latest changes. I'm going to confirm tomorrow 11/7/2019

**Comment by robertojrojas** [comment]
cc: @hectoralicea 

Well, it turns out that for AKS passing the **"--version"** flag might be the only option for the moment.
As of kube-bench v0.1.0, using only **`command: ["kube-bench"]`** the following error is returned 
```console
Unable to find the programs kubectl or kubelet in the PATH.
...
Alternatively, you can specify the version with --version
   kube-bench --version <VERSION> ...
```

I found that **kubectl** is located in **'/usr/local/bin'**  instead of **'/usr/bin'**
I also noticed that the **kubectl** executable is dynamically linked with **GLIBC**, which is not compatible with the **Alpine** container kube-bench uses. So, even if we were to map **'/usr/local/bin'** into the container, **kube-bench** won't be able to successfully execute it.

Here are a few tests I performed to arrive to this conclusion. Notice that I'm mapping the host's **'/'** to **'/host'**. This is to be able to use the Alpine compatible version of **file**, **ldd**, and **objump** :

```console
#file /host/usr/local/bin/kubectl
/host/usr/local/bin/kubectl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), 
dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, 
for GNU/Linux 2.6.32, Go BuildID=89ae892d3587d4b4faad255e8407aed2ebae401f, 
BuildID[sha1]=b6c2a3fb89f8d3d70988a2b0c4f7bb0b101784f9, with debug_info, not stripped


#ldd /host/usr/local/bin/kubectl
	/lib64/ld-linux-x86-64.so.2 (0x7f5bf7e1c000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f5bf7e1c000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f5bf7e1c000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f5bf7e1c000)

#/objdump -p /host/usr/local/bin/kubectl | grep NEEDED
  NEEDED               libpthread.so.0
  NEEDED               libdl.so.2
  NEEDED               libc.so.6
  
```

**Comment by robertojrojas** [comment]
@hectoralicea I'm working on a PR #518  that might help with the situation where **kube-bench** is having a hard time determining the **Kubernetes** version.

**Comment by robertojrojas** [comment]
@hectoralicea PR #518 should provide a solution for this.
Closing...
