### ISSUE TITLE
Not-Scored issues are marked as warnings without any info

### ISSUE THREAD

**Issue by YuvalAqua** [aquasecurity/kube-bench#427]
Warning is too general to understand in order to make a decision. 
we describe a test which is not scored but-
Did the test pass? fail? was not successfully executed?
We need to provide the user with information he can act upon or at least understand his status

**Comment by lizrice** [comment]
[Warn](https://github.com/aquasecurity/kube-bench#output) means that the test could not be run, and needs further attention from the user. 

- If the test is Manual, this always generates WARN (because the user has to run it manually) 
- If the test is Scored, and we were unable to run the test, this generates FAIL (because the test has not been passed, and as a Scored test, if it doesn't pass then it must be considered a failure).
- If the test is Not Scored, and we were unable to run the test, this generates WARN. 

I'm going to add this to the README for clarification. Does that give you what you need?

**Comment by YuvalAqua** [comment]
I think there is a difference between not able to perform and failed. also, if it's manual there should be a better notification than WARN which can mean few reasons.

**Comment by lizrice** [comment]
Maybe the solution here is to add some extra information in the event when kube-bench could not run the test (as opposed to running the test but it fails the test criteria).

**Comment by robertojrojas** [comment]
Scheduled a meeting with @YuvalAqua for Monday 11/11/2019 to talk about this.

**Comment by lizrice** [comment]
@robertojrojas could you write up here what conclusions you & Yuval came to? This might be something @yoavrotems could work on

**Comment by robertojrojas** [comment]
@yoavrotems @lizrice, @YuvalAqua and I agreed that new a new section should be added to the JSON output. 
This section should include which, if any, tests failed due to execution errors vs outcome from the test of the results of the command execution.  
I'm proposing adding a the field `CommandError` to the `check.Check` struct like so:
```
type Check struct {
...
CommandError   string `json:"command_error,omitempty"`
}
```
The field `CommandError` will be populated when the command is executed and Operating System reports an error. For example:
```
# /usr/bin/ps aux
sh: /usr/bin/ps: not found
```
The field `CommandError` should be populated with `sh: /usr/bin/ps: not found`

For example,
```console
{
  "id": "2",
  "version": "1.13",
  "text": "Worker Node Security Configuration",
  "node_type": "node",
  "tests": [
    {
      "section": "2.x",
      ...
      "results": [
        {
          "test_number": "2.x.y",
          "test_desc": "example command (Not Scored)",
          "audit": "/usr/bin/ps -fC some",
          ...
          "status": "WARN",
          ...
          "command_error": "sh: /usr/bin/ps: not found"
        },

...
}
```
If no errors have been reported by the OS, the field `CommandError` will not be populated, which means it will not be included as part of the JSON output.

Since this new field will mainly be used to provide more information for situations when Test is flagged as **scored: false or (Not Scored)** , I suggest making changes to the following part of the code:


```
if finalOutput != nil && finalOutput.testResult {
		...
	} else {
		if c.Scored {
			c.State = FAIL
		} else {
			c.State = WARN
                        // ISSUE 427 Changes should go here!
		}
	}
```

wdyt?

**Comment by leodotcloud** [comment]
Instead of naming it `warn_reason`, may be it could be kept generic as `reason` so that more info can be added in case of FAIL too?
