### ISSUE TITLE
Support detecting etcd arguments via env vars

### ISSUE THREAD

**Issue by rifelpet** [aquasecurity/kube-bench#667]
Kops uses environment variables to configure etcd arguments like cert-file and key-file. See all of the `ETCD_*` env vars documented [here](https://etcd.io/docs/v3.4.0/op-guide/configuration/) as well as this example:

https://github.com/kopeio/etcd-manager/blob/26ca2ad568e9819f04cf00f43d79bd76c5f9dfb3/pkg/etcd/etcdprocess.go#L229-L241

Currently kube-bench reports that these arguments are not set because only process arguments are checked:

https://github.com/aquasecurity/kube-bench/blob/a6161aa8684818157d583e1e64b56d4c6b51046d/cfg/cis-1.5/etcd.yaml#L13-L20

It would be great to also check the etcd process' environment variables in determining whether they're set.

**Comment by ankitsrao** [comment]
I agree with @rifelpet . Maybe this is the reason why, for the etcd policies, the status remains FAIL, even though we follow the remediation procedure.
Anyone else facing the same issue?

**Comment by lizrice** [comment]
I've raised a ticket about this on the CIS benchmark too because the recommendations should really reflect this as well. 

Getting the environment variables for another process is possible via the `/proc` directory on the host but this is not going to be a trivial change to make. (Unless there is a way to query etcd's configuration over an API?)

In the mean time you may prefer to [skip](https://github.com/aquasecurity/kube-bench#omitting-checks) these tests
