### ISSUE TITLE
SecurityHub report duplicated

### ISSUE THREAD

**Issue by steve-heslouin** [aquasecurity/kube-bench#879]
**Overview**

I ran the **job-eks-asff.yaml** couple of times for the same cluster, like if i would do it periodically on a weekly basis for example, and it created as much duplicated entry in security hub as the amount of times i ran it. Example:

<img width="1283" alt="Screenshot 2021-05-25 at 16 23 12" src="https://user-images.githubusercontent.com/50872822/119515590-49fc6380-bd76-11eb-8f1a-eb370a3243a0.png">

**How did you run kube-bench?**

kubectl apply -f job-eks-asff.yaml

**What happened?**

No error, the job ran correctly 

**What did you expect to happen:**

Only one entry in security hub per issue found, that is being updated , not creating a new one each times

**Environment** 

latest from github

[What is your version of Kubernetes? (run `kubectl version` or `oc version` on OpenShift.)]

1.20

**Running processes**

N/A

**Configuration files**

N/A

**Anything else you would like to add:**

N/A

**Comment by steve-heslouin** [comment]
anyone?

**Comment by yoavrotems** [comment]
Hey sorry for the late response, I will start with a confession I didn't used AWS security hub so I might not understanding something correctly but to may understand kube-bench is only pushing new results with asff.
As you run it, it will push new results to the security hub and I guess that aws will separate in because it doesn't follow aggregation rules.
Maybe there is a way to unite scans in the security hub? 
wdyt?

**Comment by yoavrotems** [comment]
Hey @steve-heslouin I'm closing this issue waiting for you response, if you any more questions or or information to share please reopen this issue
