### ISSUE TITLE
False positive findings for EKS and AKS based Kubernetes clusters

### ISSUE THREAD

**Issue by ankitsrao** [aquasecurity/kube-bench#940]
**Overview**

Hi Team, 

I'm working on a short POC around fetching CIS Kubernetes Benchmark v1.5.0 and analysing the kube-bench results for EKS and AKS. But it seems that kube-bench is returning false positives for some of the CIS controls, mostly the CIS controls illustrating the file permissions [ Controls 4.1.1 to 4.1.10 ]

**How did you run kube-bench?**

I'm running the kube-bench container with below below command :
 ` kube-bench --benchmark cis-1.5 `

**What happened?**

For control numbers 4.1.1 to 4.1.10, kube-bench returns a 'False' status even though appropriate file permissions are configured.
In some cases, even if the files are not present kube-bench returns the status as FAIL.

**What did you expect to happen:**

- The policy status should return PASS, or it should return WARN, if it is not able to file the files.

**Environment** 

[What is your version of kube-bench? (run `kube-bench version`)]

Using the latest kube-bench version : aquasec/kube-bench:latest

[What is your version of Kubernetes? (run `kubectl version` or `oc version` on OpenShift.)]

EKS K8s version 1.20

**Running processes**

NA. This is just a demo cluster and it just has the normal kube-system proccesses and a cronjob that I'm running

**Anything else you would like to add:**

It seems that the latest version release may have introduced this issue, as earlier the data returned was appropriate.
Further, I'm using the "cis-1.5" benchmark parameter for both EKS and AKS. I hope that should not be the cause of the issue.

-TIA

**Comment by yoavrotems** [comment]
Hey, I think its relate to other issues we have with latest keep building from each PR which causing some unstable behaviors could you please try running it with tag 0.6.3 and see if the errors still occurs? 
And if so please attach more loggings (run it with -v 3 flag) and then we could see why its failing the tests

**Comment by ankitsrao** [comment]
Hi @yoavrotems ,

Thank you for the revert and apologies for the late response from my end.
So I tried out to fetch the findings with the kube-bench version 0.6.0 , and I'm different data ( as expected) as compared to when I run the latest version of kube-bench. I've attached the log files using both the image versions for your referance.

[kube-bench-latest-logfile.txt](https://github.com/aquasecurity/kube-bench/files/6941536/kube-bench-latest-logfile.txt)
[kube-bench-v0-6-0-logfile.txt](https://github.com/aquasecurity/kube-bench/files/6941537/kube-bench-v0-6-0-logfile.txt)

Anticipating a response to clarify the different results on the same EKS cluster with different kube-bench version.

-TIA

**Comment by yoavrotems** [comment]
Ok did you ran kube-bench binaries ? or a job? or with docker? 
Because the main difference between the logs you sent me is that the latest one seems to missing env libs 
`I0805 20:20:05.441335   30268 check.go:186] Command: "/bin/sh -c 'if test -e /etc/systemd/system/kubelet.service; then stat -c permissions=%a /etc/systemd/system/kubelet.service; fi' " TestResult: <<EMPTY>> `
So if you are running it locally could something changed in your env? 
And if you running it using docker or kubernetes job something could be broke from our side. 

**Note**
About the initial issue you had with 4.1.1 and 4.1.10 as I can see in the version it worked (0.6.0) both pass since the file permissions are 644 (correct me if I'm wrong) 

**Note 2**
The latest stable version is 0.6.3

**Comment by ankitsrao** [comment]
Hi @yoavrotems ,
The utility was run as a Job for both the versions and on the same EKS cluster.
So ideally , we should not see different responses , just because of using different kube-bench versions.

Thanks,

**Comment by yoavrotems** [comment]
I will need to further investigating it if you just ran it as job. 

> So ideally , we should not see different responses , just because of using different kube-bench versions.

Ideally we shouldn't see different output, but kube-bench is evolving, we are making upgrades, fixing bugs, updating images and envs we use, it only reasonable that there will be changes in the engine and output from version to version, we just need to keep in track that nothing is breaking. 

Back to the subject, I will investigate the other issue regarding to the missing libs (could be relate to update image), but as I can see from the logs you sent in version 0.6.0 both your check 4.1.1 and 4.1.10 have PASS status, and from the data it seems that it really should pass and all is good.
I checked version 0.6.3 as well and it passed too.
Regarding to it fail when file doesn't exist this is currently the logic, since we check for expected permission if there isn't permission it doesn't set the engine expectation and fail, if you believe there is a better logic to apply here you are more then welcome to open a discussion in the subject and we can discuss that there.

**Comment by ankitsrao** [comment]
`I checked version 0.6.3 as well and it passed too.`

I guess there is a miss here. The log file I shared for the latest version marks controls 4.1.1 to 4.1.10 all FAIL , whereas kube-bench v0.6.0 marks them PASS

Also to clarify, this is not just about 2 controls, this discrepancy is for 10 CIS controls , including all CIS controls from 4.1.1 to 4.1.10, which I feel is alarming.

Thanks,
